#!/usr/bin/env bash

set -e 

# gcc -O3 -o proxy proxy.c
[ -f config.h ] || cp config.def.h config.h
gcc -O0 -g -o proxy proxy.c

if [ "$1" = "run" ]; then 
  if pgrep -x "proxy"; then
    pkill -x "proxy"
  fi
  while true; do
    ./proxy
    echo "Exited D: ($?)"
  done;
fi

