#!/usr/bin/env bash

# gcc -O3 -o proxy proxy.c
[ -f config.h ] || cp config.def.h config.h
gcc -O0 -g -o proxy proxy.c || exit 1

{ if [ "$1" = "run" ]; then 
  # Allow failures again
  pkill -x "proxy"
  while true; do
    ./proxy
    echo "Exited D: ($?)"
    sleep 1
  done;
fi
} & disown
